/**
 * @file test_crc.h
 * @brief A description of the template's purpose.
 * @copyright Copyright (c) 2023 ChipWon Technology. All rights reserved.
 */

#ifndef TEST_CRC_H_
#define TEST_CRC_H_

#ifdef __cplusplus
extern "C" {
#endif

/*******************************************************************************
 * Macros, defines, enumerations, structures(with typedefs)
 ******************************************************************************/
typedef struct
{
    char            name[32];
    crc_bit_width_t crc_width;           // Algorithm
    crc_transpose_t read_transpose;      // TOTR
    crc_transpose_t write_transpose;     // TOT
    bool            b_complement_checksum; // FXOR
    uint32_t        polynomial;
    uint32_t        seed; // INIT
    uint8_t         crc_data_size;
    uint8_t         crc_data[64];
    uint32_t        crc_result;
} crc_table_t;

/*******************************************************************************
 * Exported variables
 ******************************************************************************/
crc_table_t crc_table[] = {{"CRC5_EPC",
                            CRC_BITS_5,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0x09,
                            0x09,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x0A},
                           {"CRC5_ITU",
                            CRC_BITS_5,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            false,
                            0x15,
                            0x00,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x0A},
                           {"CRC5_USB",
                            CRC_BITS_5,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            true,
                            0x05,
                            0x1F,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x1B},
                           {"CRC8",
                            CRC_BITS_8,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0x07,
                            0x00,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x11},
                           {"CRC8_SAE_J1850",
                            CRC_BITS_8,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            true,
                            0x1D,
                            0xFF,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x1A},
                           {"CRC8_SAE_J1850_ZERO",
                            CRC_BITS_8,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0x1D,
                            0x00,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x43},
                           {"CRC8_8H2F",
                            CRC_BITS_8,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            true,
                            0x2F,
                            0xFF,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xF3},
                           {"CRC8_CDMA2000",
                            CRC_BITS_8,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0x9B,
                            0xFF,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x8E},
                           {"CRC8_DARC",
                            CRC_BITS_8,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            false,
                            0x39,
                            0x00,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xDE},
                           {"CRC8_DVB_S2",
                            CRC_BITS_8,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0xD5,
                            0x00,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xAA},
                           {"CRC8_EBU",
                            CRC_BITS_8,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            false,
                            0x1D,
                            0xFF,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x53},
                           {"CRC8_I_CODE",
                            CRC_BITS_8,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0x1D,
                            0xFD,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xC2},
                           {"CRC8_MAXIM",
                            CRC_BITS_8,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            false,
                            0x31,
                            0x00,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xEE},
                           {"CRC8_ROHC",
                            CRC_BITS_8,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            false,
                            0x07,
                            0xFF,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xA5},
                           {"CRC8_WCDMA",
                            CRC_BITS_8,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            false,
                            0x9B,
                            0x00,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x33},
                           {"CRC16_CCITT_FALSE",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0x1021,
                            0xFFFF,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x39A3},
                           {"CRC16_CCITT_FALSE",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0x1021,
                            0xFFFF,
                            20,
                            {0xE0, 0xFF, 0x21, 0x94, 0xA6, 0x02, 0x08, 0x7C, 0x18, 0x00,
                             0xC1, 0xBF, 0x24, 0x00, 0x01, 0x90, 0x00, 0x00, 0xE0, 0x3B},
                            0x37D9},
                           {"CRC16_ARC",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            false,
                            0x8005,
                            0x0000,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xF1E},
                           {"CRC16_ARC",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            false,
                            0x8005,
                            0x0000,
                            20,
                            {0xE0, 0xFF, 0x21, 0x94, 0xA6, 0x02, 0x08, 0x7C, 0x18, 0x00,
                             0xC1, 0xBF, 0x24, 0x00, 0x01, 0x90, 0x00, 0x00, 0xE0, 0x3B},
                            0x99D2},
                           {"CRC16_AUG_CCITT",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0x1021,
                            0x1D0F,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xB373},
                           {"CRC16_BUYPASS",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0x8005,
                            0x0000,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xC959},
                           {"CRC16_CCITT_ZERO",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0x1021,
                            0x0000,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xBD63},
                           {"CRC16_CDMA2000",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0xC867,
                            0xFFFF,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x58BF},
                           {"CRC16_DDS_110",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0x8005,
                            0x800D,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xC981},
                           {"CRC16_DECT_R(custom)",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            true,
                            0x589,
                            0x0000,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x2255},
                           {"CRC16_DECT_X",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0x589,
                            0x0000,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xCF74},
                           {"CRC16_DNP",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            true,
                            0x3D65,
                            0x0000,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xDE0},
                           {"CRC16_EN_13755(custom)",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            true,
                            0x3D65,
                            0x0000,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x5AD1},
                           {"CRC16_GENIBUS(custom)",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            true,
                            0x1021,
                            0xFFFF,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x66E1},
                           {"CRC16_MAXIM",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            true,
                            0x8005,
                            0x0000,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xF0E1},
                           {"CRC16_MCRF4XX",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            false,
                            0x1021,
                            0xFFFF,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x991E},
                           {"CRC16_RIEELO",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            false,
                            0x1021,
                            0xB2AA,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xBD59},
                           {"CRC16_T10_DIF",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0x8BB7,
                            0x0000,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x19E5},
                           {"CRC16_TELEDISK",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0xA097,
                            0x0000,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x13E3},
                           {"CRC16_TMS37157",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            false,
                            0x1021,
                            0x89EC,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x62E0},
                           {"CRC16_USB",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            true,
                            0x8005,
                            0xFFFF,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xD4E1},
                           {"CRC16_A",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            false,
                            0x1021,
                            0xC6C6,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xCC3F},
                           {"CRC16_KERMIT",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            false,
                            0x1021,
                            0x0000,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x9A3F},
                           {"CRC16_MODBUS",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            false,
                            0x8005,
                            0xFFFF,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x2B1E},
                           {"CRC16_X_25",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            true,
                            0x1021,
                            0xFFFF,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0x66E1},
                           {"CRC16_XMODEM",
                            CRC_BITS_16,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0x1021,
                            0x0000,
                            4,
                            {0xE0, 0xFF, 0x21, 0x94},
                            0xBD63},
                           {"CRC32",
                            CRC_BITS_32,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            true,
                            0x4C11DB7,
                            0xFFFFFFFF,
                            20,
                            {0xE0, 0xFF, 0x21, 0x94, 0xA6, 0x02, 0x08, 0x7C, 0x18, 0x00,
                             0xC1, 0xBF, 0x24, 0x00, 0x01, 0x90, 0x00, 0x00, 0xE0, 0x3B},
                            0xA7C4592A},
                           {"CRC32_BZIP2",
                            CRC_BITS_32,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            true,
                            0x4C11DB7,
                            0xFFFFFFFF,
                            20,
                            {0xE0, 0xFF, 0x21, 0x94, 0xA6, 0x02, 0x08, 0x7C, 0x18, 0x00,
                             0xC1, 0xBF, 0x24, 0x00, 0x01, 0x90, 0x00, 0x00, 0xE0, 0x3B},
                            0x9F3D779E},
                           {"CRC32_C",
                            CRC_BITS_32,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            true,
                            0x1EDC6F41,
                            0xFFFFFFFF,
                            20,
                            {0xE0, 0xFF, 0x21, 0x94, 0xA6, 0x02, 0x08, 0x7C, 0x18, 0x00,
                             0xC1, 0xBF, 0x24, 0x00, 0x01, 0x90, 0x00, 0x00, 0xE0, 0x3B},
                            0x24A8D152},
                           {"CRC32_D",
                            CRC_BITS_32,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            true,
                            0xA833982B,
                            0xFFFFFFFF,
                            20,
                            {0xE0, 0xFF, 0x21, 0x94, 0xA6, 0x02, 0x08, 0x7C, 0x18, 0x00,
                             0xC1, 0xBF, 0x24, 0x00, 0x01, 0x90, 0x00, 0x00, 0xE0, 0x3B},
                            0xCDEA0DD8},
                           {"CRC32_MPEG2",
                            CRC_BITS_32,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0x4C11DB7,
                            0xFFFFFFFF,
                            20,
                            {0xE0, 0xFF, 0x21, 0x94, 0xA6, 0x02, 0x08, 0x7C, 0x18, 0x00,
                             0xC1, 0xBF, 0x24, 0x00, 0x01, 0x90, 0x00, 0x00, 0xE0, 0x3B},
                            0x60C28861},
                           {"CRC32_POSIX",
                            CRC_BITS_32,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            true,
                            0x4C11DB7,
                            0x00000000,
                            20,
                            {0xE0, 0xFF, 0x21, 0x94, 0xA6, 0x02, 0x08, 0x7C, 0x18, 0x00,
                             0xC1, 0xBF, 0x24, 0x00, 0x01, 0x90, 0x00, 0x00, 0xE0, 0x3B},
                            0xD11B2391},
                           {"CRC32_Q",
                            CRC_BITS_32,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0x814141AB,
                            0x00000000,
                            20,
                            {0xE0, 0xFF, 0x21, 0x94, 0xA6, 0x02, 0x08, 0x7C, 0x18, 0x00,
                             0xC1, 0xBF, 0x24, 0x00, 0x01, 0x90, 0x00, 0x00, 0xE0, 0x3B},
                            0x22145D58},
                           {"CRC32_JAMCRC",
                            CRC_BITS_32,
                            CRC_TRANSPOSE_BITS_AND_BYTES,
                            CRC_TRANSPOSE_BITS,
                            false,
                            0x4C11DB7,
                            0xFFFFFFFF,
                            20,
                            {0xE0, 0xFF, 0x21, 0x94, 0xA6, 0x02, 0x08, 0x7C, 0x18, 0x00,
                             0xC1, 0xBF, 0x24, 0x00, 0x01, 0x90, 0x00, 0x00, 0xE0, 0x3B},
                            0x583BA6D5},
                           {"CRC32_XFER",
                            CRC_BITS_32,
                            CRC_TRANSPOSE_NONE,
                            CRC_TRANSPOSE_NONE,
                            false,
                            0x000000AF,
                            0x00000000,
                            20,
                            {0xE0, 0xFF, 0x21, 0x94, 0xA6, 0x02, 0x08, 0x7C, 0x18, 0x00,
                             0xC1, 0xBF, 0x24, 0x00, 0x01, 0x90, 0x00, 0x00, 0xE0, 0x3B},
                            0xA38F0BC8}};

#ifdef __cplusplus
}
#endif

#endif /* TEST_CRC_H_ */

/*** end of file ***/
